it:
  code: ita
  name: italiano
  t:
    active_lang: lingua attiva
    cookiebar_accept: Accetto
    cookiebar_msg: Questo sito utilizza cookie tecnici, analytics e di terze parti. Proseguendo nella navigazione accetti l’utilizzo dei cookie.
    cookiebar_privacy_policy: Privacy policy
    follow_us: seguici su
    footer_address: Indirizzo
    footer_address_sub: ''
    footer_contacts: Contatti
    footer_contacts_sub: ''
    footer_link_privacy_policy: privacy policy
    footer_link_legal_notes: note legali
    footer_title: ' '
    lang_on_site: sito in italiano
    navigation_network_menu_label: Menu di navigazione del network
    navigation_menu_label: Menu di navigazione
    navigation_menu_esc: esci dalla navigazione
    scrolltop_label: torna all'inizio dei contenuti
    search_form_label: Cerca...
    search_form_off: disattiva il form di ricerca
    search_form_on: attiva il form di ricerca
    search_form_start: avvia la ricerca
    site_subtitle: dalla parte dei cittadini
    site_title: designers Italia
    share_msg: condividi
    skiplink_goto_content: vai ai contenuti
    skiplink_goto_navigation: vai alla navigazione del sito
    toggle_menu_label: accedi al menu
    toggle_network_menu_label: accedi al menu del network

    header_link_trasformazione: Piano Triennale
    header_link_developers: Developers
    header_link_design: Designers
    header_link_forum: Forum
    header_link_docs: Docs
    header_link_github: GitHub

    by: di
    on_: "su"
    coming_soon: in arrivo
    news_categories: argomenti
    news_title: Storie
    news_nav_title: Tag sul blog Medium
    see_all: vedi tutti
    last_related: Ultime su

    paginator_previous_page: pagina precedente
    paginator_next_page: pagina successiva
    paginator_page: pagina

    home_hero: Disegniamo <strong>servizi digitali semplici</strong><br> per <strong>risolvere i problemi dei cittadini</strong>
    home_hero_sub: e restituire il <strong>buonumore</strong> ;-)
    home_medium_text: Approfondisci su <strong>Medium</strong>
    home_medium_label: leggi il post
    home_newsletter_title: Iscriviti alla <strong>newsletter</strong>
    home_newsletter_placeholder: indirizzo email
    home_newsletter_button: Iscriviti
    home_designkit_title: I design kit
    home_designkit_subtitle: Risorse condivise per progettare, realizzare e migliorare i servizi digitali della Pubblica Amministrazione
    home_designkit_action: 'Scopri <a href="/come-lo-uso" class="u-text-r-xs u-textWeight-400 u-color-50">come usare</a> i design kit'
    home_designkit_button: Esplora i design kit
    home_grids_title: Le linee guida
    home_grids_subtitle: La documentazione che ti insegna a progettare mettendo il cittadino al centro
    home_grids_button: Apri le linee guida
    home_projects: i progetti
    home_projects_title: Progetti
    home_projects_subtitle: Servizi digitali a misura di cittadino.
    home_projects_footer: Usateli nei vostri progetti e contribuite a migliorarne il design !
    home_projects_expand: per saperne di più
    home_projects_others: Tutti i progetti
    home_projects_count: progetti in totale
    home_news_title: Novità
    home_news_expand: per saperne di più
    home_forum_title: Forum
    home_forum_subtitle: Si parla di (quasi) tutto, un po’ come in famiglia
    home_forum_action: partecipa
    home_forum_link: forum.italia.it/c/design
    home_description: "<strong>Designers Italia</strong> è il punto di riferimento per il design della Pubblica Amministrazione: [guide](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/it/stabile/doc/introduzione-linee-guida-design.html), [strumenti](/kit) e un [forum](https://forum.italia.it/c/design) per favorire la collaborazione e promuovere il ruolo dello <strong>human centered design</strong> nello sviluppo dei servizi pubblici."

    home_blog_title: Storie
    home_blog_subtitle: Cose che ci piacciono
    home_blog_tag_1: case histories
    home_blog_tag_2: tendenze
    home_blog_tag_3: risorse
    home_blog_text:

    credits_contributors: "Con la partecipazione di:"

    status_maintainer: maintainer

    in_collaboration_with: In collaborazione con

    main_menu_label: Il Design System della Pubblica Amministrazione Italiana

    download_please: Scarica

    formatDate: "%d/%m/%Y"

en:
  code: eng
  name: english
  t:
    active_lang: current language
    cookiebar_accept: Accept
    cookiebar_msg: We are using cookies to provide statistics that help us give you the best experience of our site. By continuing to use the site you are agreeing to our use of cookies.
    cookiebar_privacy_policy: Privacy policy
    follow_us: follow us
    footer_address: Address
    footer_address_sub: ''
    footer_contacts: Contacts
    footer_contacts_sub: ''
    footer_link_privacy_policy: privacy policy
    footer_link_legal_notes: terms and conditions
    footer_title: ' '
    lang_on_site: website in english
    navigation_menu_label: Navigation menu
    navigation_menu_esc: exit navigation
    scrolltop_label: back to contents
    search_form_label: Search...
    search_form_off: exit search form
    search_form_on: enter search form
    search_form_start: start searching
    site_subtitle: The Italian community of designers of public services
    site_title: designers Italia
    share_msg: share
    skiplinks_goto_content: go to content
    skiplinks_goto_navigation: go to site navigation
    toggle_menu_label: go to navigation

    header_link_trasformazione: Piano Triennale ICT
    header_link_developers: Developers
    header_link_design: Designers
    header_link_forum: Forum
    header_link_docs: Docs
    header_link_github: GitHub

    by: by
    on_: "on"
    coming_soon: coming soon
    news_categories: tags
    news_title: News
    news_nav_title: Categories
    last_related: The latest on

    paginator_previous_page: previous page
    paginator_next_page: next page
    paginator_page: page

    home_hero: We design simple public services to solve people problems
    home_hero_sub: and give back some <strong>happiness</strong> ;-)
    home_medium_text: Read on <strong>Medium</strong>
    home_medium_label: read the post
    home_newsletter_title: Subscribe to our Newlsetter
    home_newsletter_placeholder: email address
    home_newsletter_button: Subscribe
    home_projects_title: Highlighted projects
    home_projects_expand: read more
    home_projects_others: All the projects
    home_projects_count: total projects
    home_news_title: News
    home_news_expand: read more
    home_description:

    credits_contributors: Project contributors

    status_member_of_board: member of board
    status_maintainer: maintainer

    in_collaboration_with: In collaboration with

    main_menu_label: Italian Public Administration Design System

    download_please: Download

    formatDate: "%m/%d/%Y"
