name: Apri una segnalazione - IT 🇮🇹
description: Per segnalare bug, aprire una discussione o inviare un contributo
title: "<title>"
labels: []
body:
- type: checkboxes
  attributes:
    label: Esiste già una discussione sul tema che ti interessa, o su un tema simile?
    description: Se esiste, vai alla discussione esistente e partecipa lasciando un commento.
    options:
    - label: | 
        Ho verificato nella [lista delle discussioni](https://github.com/italia/designers.italia.it/issues/)
      required: true
- type: textarea
  attributes:
    label: Tema della segnalazione
    description: |
      > Descrivi in modo chiaro e conciso il tema della tua segnalazione indicando il link della pagina o delle pagine interessate.
      > Per segnalare un bug indica come riprodurlo per passi: es. (1) Vai a '...'; (2) Fai click su '...'; (3) Ora trovi il bug '...'.
      > Per proporre un contributo descrivi la soluzione che immagini, cosa ti aspetti e le eventuali alternative hai già valutato. 
  validations:
    required: true
